// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKqMRnhoflJoW75NqMemoW6hq98ZUujPM',
    appId: '1:428088769000:web:2a912190f265cf91ebcc5d',
    messagingSenderId: '428088769000',
    projectId: 'flutter-to-do-list-687ef',
    authDomain: 'flutter-to-do-list-687ef.firebaseapp.com',
    storageBucket: 'flutter-to-do-list-687ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7X6XikjgGdBdymvV4XwSW75sokAHOewI',
    appId: '1:428088769000:android:aade4c93cc26fcc6ebcc5d',
    messagingSenderId: '428088769000',
    projectId: 'flutter-to-do-list-687ef',
    storageBucket: 'flutter-to-do-list-687ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUL7Pk33g-gtQm409hQcwOa__2uLhMlp4',
    appId: '1:428088769000:ios:abc430d3c2728607ebcc5d',
    messagingSenderId: '428088769000',
    projectId: 'flutter-to-do-list-687ef',
    storageBucket: 'flutter-to-do-list-687ef.firebasestorage.app',
    iosClientId: '428088769000-599nnd30u4228v4lfmka6u9iedqrva5q.apps.googleusercontent.com',
    iosBundleId: 'com.zejnepajdynkyzy.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUL7Pk33g-gtQm409hQcwOa__2uLhMlp4',
    appId: '1:428088769000:ios:09a0b6f813e387e8ebcc5d',
    messagingSenderId: '428088769000',
    projectId: 'flutter-to-do-list-687ef',
    storageBucket: 'flutter-to-do-list-687ef.firebasestorage.app',
    iosClientId: '428088769000-4f4r7e1f5k9ila4vp9gnokkik74gkh1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKqMRnhoflJoW75NqMemoW6hq98ZUujPM',
    appId: '1:428088769000:web:12f71df5cd9a7a2eebcc5d',
    messagingSenderId: '428088769000',
    projectId: 'flutter-to-do-list-687ef',
    authDomain: 'flutter-to-do-list-687ef.firebaseapp.com',
    storageBucket: 'flutter-to-do-list-687ef.firebasestorage.app',
  );

}